[/Script/GameplayTags.GameplayTagsList]
; 在这里添加你的 GameplayTags，每行一个
GameplayTagList=(Tag="SimplePoiPlugin.WidgetAction.Click",DevComment="插件umg按钮点击")
GameplayTagList=(Tag="SimplePoiPlugin.WidgetAction.Enable",DevComment="插件umg启用")
GameplayTagList=(Tag="SimplePoiPlugin.WidgetAction.Disable",DevComment="插件umg禁用")
GameplayTagList=(Tag="SimplePoiPlugin.WidgetAction.Change",DevComment="插件umg切换")
GameplayTagList=(Tag="SimplePoiPlugin.PoiAction.Selected",DevComment="Poi组件选中")
GameplayTagList=(Tag="SimplePoiPlugin.PoiAction.Focus",DevComment="Poi组件聚焦")
